Update Package.swift
apple/swift-package-collection-generator pull request #64
Opened 2024-03-14 22:39 UTC by danibachar

Bumping to support macv13 + pinning spm to the latest production release (version 5.1))

2024-03-14 22:43 UTC, danibachar commented
Currently the package does not build because its pointing to [SPM](https://github.com/apple/swift-package-collection-generator) main - which is not supporting macos_v12

2024-03-14 23:55 UTC, yim-lee requested changes
Thanks for the PR. I think we only need the change in `platforms` to fix `main`.

2024-03-14 23:55 UTC, yim-lee commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-package-manager.git", revision: "82e3974c7714783bab1da11e29d053422fdfba9a"), // 5.10 Release
I created a new branch `5.10` in this repo that points to SwiftPM's `release/5.10` branch. Let's keep the `branch: "main"` here.

2024-03-15 00:12 UTC, danibachar commented
Thanks for the quick response, you are correct only the platform change is needed - i reverted the branch change.

2024-03-15 00:15 UTC, yim-lee approved these changes

2024-03-15 00:15 UTC, merged